services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: criminal-case-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - web-app_default

networks:
  web-app_default:
    external: true

volumes:
  pgadmin_data:
