from fastapi import APIRouter
from . import auth, bank_accounts, non_bank_accounts, non_bank_transactions, payment_gateway_accounts, payment_gateway_transactions, telco_mobile_accounts, telco_internet_accounts, suspects, criminal_cases, post_arrests, documents, case_types, courts, pdf_parser, police_stations, user_registration, admin_users, cfr_upload, master_data, emails, email_tracking, profile
from .endpoints import banks, non_banks, payment_gateways, telco_mobile, telco_internet, exchanges, organizations, charges

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["authentication"])
api_router.include_router(profile.router, prefix="/profile", tags=["profile"])
api_router.include_router(user_registration.router, prefix="/registration", tags=["user-registration"])
api_router.include_router(admin_users.router, prefix="/admin", tags=["admin-users"])
api_router.include_router(organizations.router, prefix="/organizations", tags=["organizations"])
api_router.include_router(banks.router, prefix="/banks", tags=["banks"])
api_router.include_router(non_banks.router, prefix="/non-banks", tags=["non-banks"])
api_router.include_router(payment_gateways.router, prefix="/payment-gateways", tags=["payment-gateways"])
api_router.include_router(telco_mobile.router, prefix="/telco-mobile", tags=["telco-mobile"])
api_router.include_router(telco_internet.router, prefix="/telco-internet", tags=["telco-internet"])
api_router.include_router(exchanges.router, prefix="/exchanges", tags=["exchanges"])
api_router.include_router(charges.router, prefix="/charges", tags=["charges"])
api_router.include_router(courts.router, prefix="/courts", tags=["courts"])
api_router.include_router(bank_accounts.router, prefix="/bank-accounts", tags=["bank-accounts"])
api_router.include_router(non_bank_accounts.router, prefix="/non-bank-accounts", tags=["non-bank-accounts"])
api_router.include_router(payment_gateway_accounts.router, prefix="/payment-gateway-accounts", tags=["payment-gateway-accounts"])
api_router.include_router(non_bank_transactions.router, prefix="/non-bank-transactions", tags=["non-bank-transactions"])
api_router.include_router(payment_gateway_transactions.router, prefix="/payment-gateway-transactions", tags=["payment-gateway-transactions"])
api_router.include_router(telco_mobile_accounts.router, prefix="/telco-mobile-accounts", tags=["telco-mobile-accounts"])
api_router.include_router(telco_internet_accounts.router, prefix="/telco-internet-accounts", tags=["telco-internet-accounts"])
api_router.include_router(suspects.router, prefix="/suspects", tags=["suspects"])
api_router.include_router(criminal_cases.router, prefix="/criminal-cases", tags=["criminal-cases"])
api_router.include_router(post_arrests.router, prefix="/post-arrests", tags=["post-arrests"])
api_router.include_router(documents.router, prefix="/documents", tags=["documents"])
api_router.include_router(case_types.router, tags=["case-types"])
api_router.include_router(pdf_parser.router, tags=["pdf-parser"])
api_router.include_router(police_stations.router, prefix="/police-stations", tags=["police-stations"])
api_router.include_router(cfr_upload.router, prefix="/cfr", tags=["cfr"])
api_router.include_router(master_data.router, prefix="/master-data", tags=["master-data"])
api_router.include_router(emails.router, prefix="/emails", tags=["emails"])
api_router.include_router(email_tracking.router, prefix="/email-tracking", tags=["email-tracking"])